### ISSUE TITLE
Version 3.0.6 requires PHP 7.x, but it is not required

### ISSUE THREAD

**Issue by DrillSergeant** [neos/typo3cr-search#32]
We use this package in dozends of Neos projects. Some of them are still Neos 3.3 (Flow 4.x). Since the last release 3.0.6 the search in our Neos 3.3 projects don't run anymore, because we host them on a PHP 7.0 where void return type is not available.
This defects the search in 10 of our Neos projects where we recently rolled out patch level updates (via composer update).

A solution could be to require PHP 7.1 in this package at version 3.0.6 so composer will not fetch this version on PHP 7.0 machines.

**Comment by DrillSergeant** [comment]
As a workaround I will contraint this package to 3.0.5 in our projects.

**Comment by daniellienert** [comment]
Mhm thats pretty bad, I didn't consider that case when reviewing the change.
I would suggest to remove the void return types again and release another bugfix version. 

Then adding the PHP constraint and the void types for the next minor / major release

**Comment by daniellienert** [comment]
@DrillSergeant - would you open a PR for that?

**Comment by DrillSergeant** [comment]
@daniellienert , I am on it. PR will come today.

**Comment by DrillSergeant** [comment]
PR ready. If that could be released as 3.0.7 soonish would be great.

**Comment by DrillSergeant** [comment]
Also added a PR for re-adding the returntypes and (this time with php constraint)

**Comment by daniellienert** [comment]
Thanks @DrillSergeant, merged and released.
